FROM python:3.6.3-jessie

# Create app directory
WORKDIR /usr/src/app

COPY . .

CMD echo Hello world

ENTRYPOINT ["./start.sh"]


# docker build -t registry.cn-shenzhen.aliyuncs.com/test-wss/python3:v0.2 .
# docker push registry.cn-shenzhen.aliyuncs.com/test-wss/python3:v0.1